### ISSUE TITLE
Maybe we need a better name

### ISSUE THREAD

**Issue by daviortega** [theJensenLab/phylogician#21]
Here are some suggestions:

1. PhyloTreeVizJS - current working name
2. NATV - Not Another Tree Viewer
3. NAPTV - Not another Phylogenetics Tree Viewer

**Comment by daviortega** [comment]
4. YaP - Yet Another Phylogenetics tree viewer

**Comment by daviortega** [comment]
@tkukavica1 what do you think !?

**Comment by tkukavica1** [comment]
I put a logo/name on the current pushed version for fun. Will that work?

**Comment by daviortega** [comment]
Oh yeah... I saw it now. I think you are winning wit the logo and name! Pretty cool.

I am placing the logo here just for documentation and I will push this task to milestone 0.2 and put back on IceBox. Let's sleep on it and see if you still like it by the version 0.2.

But I think it is awesome and we should work on the details but the idea is super cool.

Logo:
![](https://github.com/theJensenLab/phyloTreeVizJS/blob/t-firstTree/phylogician_logo.png?raw=true)

**Comment by daviortega** [comment]
Phylogician it is.
