### ISSUE TITLE
zoom in and out with scroll button

### ISSUE THREAD

**Issue by daviortega** [theJensenLab/phylogician#26]

**Comment by tkukavica1** [comment]
I've been working on figuring out how to use the proper event trigger to do this.

A small question: What do you mean by scroll button? Also, should the zooming only occur if the scrolling is inside of the box with the tree in it?

Thanks! -Tony

**Comment by tkukavica1** [comment]
Two possible methods of approaching this:
*Learn to override the browser's zoom function so that the zoom only occurs for the svg element.
*Do not override the browser's function, and instead freeze the controlBar icon to a fixed location and size.

**Comment by tkukavica1** [comment]
Works (this code handles both zoom and transform):

`
svgTree.call(d3.zoom()
		.on('zoom', () => {
			g.attr('transform', d3.event.transform)
		})
	)
`
